export type LabTube = {
  id: string;
  colorKey: string; // semantic id
  colorName: { en: string; ar: string; fr: string };
  swatch: string; // hex for the cap indicator
  glow: string; // shadow color
  additive: string;
  tests: string[];
  sample: string;
  notes: string;
  warnings: string[];
  inversions?: number;
  order?: number; // order of draw
};

export const LAB_TUBES: LabTube[] = [
  {
    id: "lavender",
    colorKey: "lavender",
    colorName: { en: "Lavender / Purple", ar: "بنفسجي", fr: "Lavande / Violet" },
    swatch: "#8b5cf6",
    glow: "139,92,246",
    additive: "EDTA (K2 / K3)",
    tests: ["CBC", "Hemoglobin", "Hematocrit", "Platelet count", "Reticulocytes", "HbA1c", "Blood typing"],
    sample: "Whole blood",
    notes: "Invert gently 8–10 times immediately after collection.",
    warnings: ["Do NOT shake — causes hemolysis", "Fill to indicated line", "Do not centrifuge for CBC"],
    inversions: 10,
    order: 6,
  },
  {
    id: "lightblue",
    colorKey: "lightblue",
    colorName: { en: "Light Blue", ar: "أزرق فاتح", fr: "Bleu clair" },
    swatch: "#38bdf8",
    glow: "56,189,248",
    additive: "Sodium citrate 3.2%",
    tests: ["PT / INR", "aPTT", "Fibrinogen", "D-dimer", "Coagulation panel"],
    sample: "Plasma (citrated)",
    notes: "Must be filled completely to maintain 9:1 blood-to-anticoagulant ratio.",
    warnings: ["Underfilled tubes invalidate results", "Invert 3–4 times gently", "Process within 1 hour"],
    inversions: 4,
    order: 2,
  },
  {
    id: "red",
    colorKey: "red",
    colorName: { en: "Red", ar: "أحمر", fr: "Rouge" },
    swatch: "#ef4444",
    glow: "239,68,68",
    additive: "None / clot activator",
    tests: ["Serology", "Blood bank", "Drug levels", "Cross-match", "Viral markers"],
    sample: "Serum",
    notes: "Allow to clot 30 minutes upright before centrifugation.",
    warnings: ["Do not invert if plain glass", "Avoid hemolysis", "Keep upright"],
    inversions: 0,
    order: 3,
  },
  {
    id: "gold",
    colorKey: "gold",
    colorName: { en: "Gold / SST", ar: "ذهبي / SST", fr: "Or / SST" },
    swatch: "#eab308",
    glow: "234,179,8",
    additive: "Clot activator + gel separator",
    tests: ["Biochemistry", "Urea", "Creatinine", "Electrolytes", "LFTs", "Lipid panel", "Hormones (TSH, T3, T4)", "Cardiac markers"],
    sample: "Serum",
    notes: "Invert 5 times. Clot 30 min then centrifuge 10 min @ 3000 rpm.",
    warnings: ["Do not freeze with gel", "Centrifuge once only", "Avoid prolonged tourniquet"],
    inversions: 5,
    order: 4,
  },
  {
    id: "green",
    colorKey: "green",
    colorName: { en: "Green", ar: "أخضر", fr: "Vert" },
    swatch: "#22c55e",
    glow: "34,197,94",
    additive: "Lithium / Sodium heparin",
    tests: ["Plasma chemistry", "Ammonia", "Electrolytes (STAT)", "Ionized calcium", "Cortisol", "Chromosome studies"],
    sample: "Plasma (heparinized)",
    notes: "Invert 8–10 times immediately. Suitable for STAT chemistry.",
    warnings: ["Not for coagulation tests", "Avoid for lithium level (use Na heparin)"],
    inversions: 10,
    order: 5,
  },
  {
    id: "gray",
    colorKey: "gray",
    colorName: { en: "Gray", ar: "رمادي", fr: "Gris" },
    swatch: "#9ca3af",
    glow: "156,163,175",
    additive: "Sodium fluoride + potassium oxalate",
    tests: ["Glucose (fasting / GTT)", "Lactate", "Alcohol level", "Glycolysis inhibition"],
    sample: "Plasma",
    notes: "Invert 8–10 times. Preserves glucose by inhibiting glycolysis.",
    warnings: ["Not for electrolytes", "Send to lab promptly"],
    inversions: 10,
    order: 7,
  },
  {
    id: "black",
    colorKey: "black",
    colorName: { en: "Black", ar: "أسود", fr: "Noir" },
    swatch: "#1f2937",
    glow: "31,41,55",
    additive: "Sodium citrate 3.8%",
    tests: ["ESR (Westergren)"],
    sample: "Whole blood",
    notes: "Fill completely. Invert 8–10 times. Run within 2 hours.",
    warnings: ["Underfilling invalidates ESR", "Keep at room temperature"],
    inversions: 10,
    order: 8,
  },
  {
    id: "royalblue",
    colorKey: "royalblue",
    colorName: { en: "Royal Blue", ar: "أزرق ملكي", fr: "Bleu royal" },
    swatch: "#1d4ed8",
    glow: "29,78,216",
    additive: "Trace-metal free (EDTA or plain)",
    tests: ["Trace elements", "Zinc", "Copper", "Lead", "Toxicology"],
    sample: "Serum / Plasma",
    notes: "Use only certified trace-metal tubes to avoid contamination.",
    warnings: ["Do not transfer to another tube", "Use dedicated needle set"],
    inversions: 8,
  },
  {
    id: "yellow",
    colorKey: "yellow",
    colorName: { en: "Yellow (ACD)", ar: "أصفر", fr: "Jaune (ACD)" },
    swatch: "#facc15",
    glow: "250,204,21",
    additive: "ACD (Acid Citrate Dextrose)",
    tests: ["HLA typing", "Paternity testing", "DNA studies", "Blood culture (SPS variant)"],
    sample: "Whole blood",
    notes: "Invert 8 times. Protect from extreme temperatures.",
    warnings: ["SPS variant is for cultures only", "Do not confuse with SST"],
    inversions: 8,
  },
  {
    id: "pink",
    colorKey: "pink",
    colorName: { en: "Pink", ar: "وردي", fr: "Rose" },
    swatch: "#ec4899",
    glow: "236,72,153",
    additive: "EDTA (K2)",
    tests: ["Blood bank / Type & Screen", "Cross-match"],
    sample: "Whole blood",
    notes: "Required by most blood banks for transfusion compatibility.",
    warnings: ["Label at bedside per protocol", "Two patient identifiers required"],
    inversions: 8,
  },
];

export const RAPID_LOOKUP: { test: string; tubeIds: string[]; hint: string }[] = [
  { test: "CBC", tubeIds: ["lavender"], hint: "Lavender EDTA" },
  { test: "PT / INR", tubeIds: ["lightblue"], hint: "Light blue citrate" },
  { test: "aPTT", tubeIds: ["lightblue"], hint: "Light blue citrate" },
  { test: "Creatinine", tubeIds: ["gold", "green"], hint: "Gold SST or Green" },
  { test: "Urea (BUN)", tubeIds: ["gold"], hint: "Gold SST" },
  { test: "Electrolytes", tubeIds: ["gold", "green"], hint: "SST or Heparin" },
  { test: "Glucose", tubeIds: ["gray"], hint: "Gray fluoride" },
  { test: "HbA1c", tubeIds: ["lavender"], hint: "Lavender EDTA" },
  { test: "ESR", tubeIds: ["black"], hint: "Black citrate" },
  { test: "Cross-match", tubeIds: ["pink", "red"], hint: "Pink EDTA / Red" },
  { test: "Troponin", tubeIds: ["gold"], hint: "Gold SST" },
  { test: "TSH / T3 / T4", tubeIds: ["gold"], hint: "Gold SST" },
  { test: "LFTs", tubeIds: ["gold"], hint: "Gold SST" },
  { test: "Lipid panel", tubeIds: ["gold"], hint: "Gold SST (fasting)" },
  { test: "Ammonia", tubeIds: ["green"], hint: "Green heparin (on ice)" },
  { test: "Lactate", tubeIds: ["gray"], hint: "Gray (on ice)" },
  { test: "D-dimer", tubeIds: ["lightblue"], hint: "Light blue citrate" },
  { test: "Blood typing", tubeIds: ["lavender", "pink"], hint: "EDTA tubes" },
];
