/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HakimRouteImport } from './routes/hakim'
import { Route as EvacuationRouteImport } from './routes/evacuation'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHakimRouteImport } from './routes/api/hakim'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HakimRoute = HakimRouteImport.update({
  id: '/hakim',
  path: '/hakim',
  getParentRoute: () => rootRouteImport,
} as any)
const EvacuationRoute = EvacuationRouteImport.update({
  id: '/evacuation',
  path: '/evacuation',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHakimRoute = ApiHakimRouteImport.update({
  id: '/api/hakim',
  path: '/api/hakim',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/evacuation': typeof EvacuationRoute
  '/hakim': typeof HakimRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/api/hakim': typeof ApiHakimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/evacuation': typeof EvacuationRoute
  '/hakim': typeof HakimRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/api/hakim': typeof ApiHakimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/evacuation': typeof EvacuationRoute
  '/hakim': typeof HakimRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/api/hakim': typeof ApiHakimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/evacuation'
    | '/hakim'
    | '/settings'
    | '/statistics'
    | '/api/hakim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/evacuation'
    | '/hakim'
    | '/settings'
    | '/statistics'
    | '/api/hakim'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/evacuation'
    | '/hakim'
    | '/settings'
    | '/statistics'
    | '/api/hakim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  EvacuationRoute: typeof EvacuationRoute
  HakimRoute: typeof HakimRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
  ApiHakimRoute: typeof ApiHakimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakim': {
      id: '/hakim'
      path: '/hakim'
      fullPath: '/hakim'
      preLoaderRoute: typeof HakimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evacuation': {
      id: '/evacuation'
      path: '/evacuation'
      fullPath: '/evacuation'
      preLoaderRoute: typeof EvacuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hakim': {
      id: '/api/hakim'
      path: '/api/hakim'
      fullPath: '/api/hakim'
      preLoaderRoute: typeof ApiHakimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  EvacuationRoute: EvacuationRoute,
  HakimRoute: HakimRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
  ApiHakimRoute: ApiHakimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
