/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PharmacistRouteImport } from './routes/pharmacist'
import { Route as NurseRouteImport } from './routes/nurse'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MapRouteImport } from './routes/map'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabTubesRouteImport } from './routes/lab-tubes'
import { Route as HakimRouteImport } from './routes/hakim'
import { Route as FermliRouteImport } from './routes/fermli'
import { Route as EvacuationRouteImport } from './routes/evacuation'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHakimRouteImport } from './routes/api/hakim'
import { Route as ApiFermliRouteImport } from './routes/api/fermli'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistRoute = PharmacistRouteImport.update({
  id: '/pharmacist',
  path: '/pharmacist',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseRoute = NurseRouteImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabTubesRoute = LabTubesRouteImport.update({
  id: '/lab-tubes',
  path: '/lab-tubes',
  getParentRoute: () => rootRouteImport,
} as any)
const HakimRoute = HakimRouteImport.update({
  id: '/hakim',
  path: '/hakim',
  getParentRoute: () => rootRouteImport,
} as any)
const FermliRoute = FermliRouteImport.update({
  id: '/fermli',
  path: '/fermli',
  getParentRoute: () => rootRouteImport,
} as any)
const EvacuationRoute = EvacuationRouteImport.update({
  id: '/evacuation',
  path: '/evacuation',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHakimRoute = ApiHakimRouteImport.update({
  id: '/api/hakim',
  path: '/api/hakim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFermliRoute = ApiFermliRouteImport.update({
  id: '/api/fermli',
  path: '/api/fermli',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/doctor': typeof DoctorRoute
  '/evacuation': typeof EvacuationRoute
  '/fermli': typeof FermliRoute
  '/hakim': typeof HakimRoute
  '/lab-tubes': typeof LabTubesRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/nurse': typeof NurseRoute
  '/pharmacist': typeof PharmacistRoute
  '/privacy': typeof PrivacyRoute
  '/select-role': typeof SelectRoleRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/terms': typeof TermsRoute
  '/api/fermli': typeof ApiFermliRoute
  '/api/hakim': typeof ApiHakimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/doctor': typeof DoctorRoute
  '/evacuation': typeof EvacuationRoute
  '/fermli': typeof FermliRoute
  '/hakim': typeof HakimRoute
  '/lab-tubes': typeof LabTubesRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/nurse': typeof NurseRoute
  '/pharmacist': typeof PharmacistRoute
  '/privacy': typeof PrivacyRoute
  '/select-role': typeof SelectRoleRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/terms': typeof TermsRoute
  '/api/fermli': typeof ApiFermliRoute
  '/api/hakim': typeof ApiHakimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/doctor': typeof DoctorRoute
  '/evacuation': typeof EvacuationRoute
  '/fermli': typeof FermliRoute
  '/hakim': typeof HakimRoute
  '/lab-tubes': typeof LabTubesRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/nurse': typeof NurseRoute
  '/pharmacist': typeof PharmacistRoute
  '/privacy': typeof PrivacyRoute
  '/select-role': typeof SelectRoleRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/terms': typeof TermsRoute
  '/api/fermli': typeof ApiFermliRoute
  '/api/hakim': typeof ApiHakimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/doctor'
    | '/evacuation'
    | '/fermli'
    | '/hakim'
    | '/lab-tubes'
    | '/login'
    | '/management'
    | '/map'
    | '/marketplace'
    | '/nurse'
    | '/pharmacist'
    | '/privacy'
    | '/select-role'
    | '/settings'
    | '/statistics'
    | '/terms'
    | '/api/fermli'
    | '/api/hakim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/doctor'
    | '/evacuation'
    | '/fermli'
    | '/hakim'
    | '/lab-tubes'
    | '/login'
    | '/management'
    | '/map'
    | '/marketplace'
    | '/nurse'
    | '/pharmacist'
    | '/privacy'
    | '/select-role'
    | '/settings'
    | '/statistics'
    | '/terms'
    | '/api/fermli'
    | '/api/hakim'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/doctor'
    | '/evacuation'
    | '/fermli'
    | '/hakim'
    | '/lab-tubes'
    | '/login'
    | '/management'
    | '/map'
    | '/marketplace'
    | '/nurse'
    | '/pharmacist'
    | '/privacy'
    | '/select-role'
    | '/settings'
    | '/statistics'
    | '/terms'
    | '/api/fermli'
    | '/api/hakim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarRoute: typeof CalendarRoute
  DoctorRoute: typeof DoctorRoute
  EvacuationRoute: typeof EvacuationRoute
  FermliRoute: typeof FermliRoute
  HakimRoute: typeof HakimRoute
  LabTubesRoute: typeof LabTubesRoute
  LoginRoute: typeof LoginRoute
  ManagementRoute: typeof ManagementRoute
  MapRoute: typeof MapRoute
  MarketplaceRoute: typeof MarketplaceRoute
  NurseRoute: typeof NurseRoute
  PharmacistRoute: typeof PharmacistRoute
  PrivacyRoute: typeof PrivacyRoute
  SelectRoleRoute: typeof SelectRoleRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
  TermsRoute: typeof TermsRoute
  ApiFermliRoute: typeof ApiFermliRoute
  ApiHakimRoute: typeof ApiHakimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist': {
      id: '/pharmacist'
      path: '/pharmacist'
      fullPath: '/pharmacist'
      preLoaderRoute: typeof PharmacistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse': {
      id: '/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-tubes': {
      id: '/lab-tubes'
      path: '/lab-tubes'
      fullPath: '/lab-tubes'
      preLoaderRoute: typeof LabTubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakim': {
      id: '/hakim'
      path: '/hakim'
      fullPath: '/hakim'
      preLoaderRoute: typeof HakimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fermli': {
      id: '/fermli'
      path: '/fermli'
      fullPath: '/fermli'
      preLoaderRoute: typeof FermliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evacuation': {
      id: '/evacuation'
      path: '/evacuation'
      fullPath: '/evacuation'
      preLoaderRoute: typeof EvacuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hakim': {
      id: '/api/hakim'
      path: '/api/hakim'
      fullPath: '/api/hakim'
      preLoaderRoute: typeof ApiHakimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fermli': {
      id: '/api/fermli'
      path: '/api/fermli'
      fullPath: '/api/fermli'
      preLoaderRoute: typeof ApiFermliRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarRoute: CalendarRoute,
  DoctorRoute: DoctorRoute,
  EvacuationRoute: EvacuationRoute,
  FermliRoute: FermliRoute,
  HakimRoute: HakimRoute,
  LabTubesRoute: LabTubesRoute,
  LoginRoute: LoginRoute,
  ManagementRoute: ManagementRoute,
  MapRoute: MapRoute,
  MarketplaceRoute: MarketplaceRoute,
  NurseRoute: NurseRoute,
  PharmacistRoute: PharmacistRoute,
  PrivacyRoute: PrivacyRoute,
  SelectRoleRoute: SelectRoleRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
  TermsRoute: TermsRoute,
  ApiFermliRoute: ApiFermliRoute,
  ApiHakimRoute: ApiHakimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
